### ISSUE TITLE
Reproduce oscillations caused by a typo in Eq 25 in the Fortran code

### ISSUE THREAD

**Issue by EmiliaJarochowska** [astro-turing/Integrating-diagenetic-equations-using-Python#39]
Charlotte discovered that [correcting a typo in the Fortran code](https://github.com/astro-turing/lheureux/commit/f3c67ecbe0f287835f44da295366618bb9b4daf7) to what was stated in the paper brought the oscillations back. After applying the typo, Fortran and rhytmite reproduce oscillations again. Try to reproduce them also with marlpde.

**Comment by EmiliaJarochowska** [comment]
Crashes with the following:
```
 34%|███████████▌                      | 10.15536/30.0 [20:15<39:35, 119.71s/it]Traceback (most recent call last):
  File "/Users/emilia/Documents/Documents - UU101746/GitHub/Integrating-diagenetic-equations-using-Python/marlpde/Evolve_scenario.py", line 143, in <module>
    integrate_equations(**all_kwargs)
  File "/Users/emilia/Documents/Documents - UU101746/GitHub/Integrating-diagenetic-equations-using-Python/marlpde/Evolve_scenario.py", line 96, in integrate_equations
    sol, info = eq.solve(state, t_range=End_time, dt=dt, \
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pde/pdes/base.py", line 591, in solve
    final_state = controller.run(state, dt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pde/solvers/controller.py", line 326, in run
    self._run_single(state, dt)
  File "/opt/homebrew/lib/python3.11/site-packages/pde/solvers/controller.py", line 206, in _run_single
    t = stepper(state, t, t_break)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pde/solvers/base.py", line 603, in wrapped_stepper
    t_last, dt_float, steps, modifications = adaptive_stepper(
                                             ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pde/solvers/base.py", line 403, in adjust_dt
    raise RuntimeError(dt_min_err)
RuntimeError: Time step below 1e-10
```

Might be related to #36 because certain combinations of Phi might overlap with the values corresponding to what is produced in this branch. Maybe worth re-running with other values of `b`.

**Comment by EmiliaJarochowska** [comment]
Ok I ran out of ideas, let's see if @HannoSpreeuw can figure this out.

**Comment by HannoSpreeuw** [comment]
Okay, so to clarify this issue: we are trying to have marlpde complete long integrations with incorrect code?
Incorrect as in: not in agreement with the paper?

**Comment by HannoSpreeuw** [comment]
I reproduced the error.

**Comment by HannoSpreeuw** [comment]
I tried `solver: str   = "adams–bashforth"` in `parameters.py`.

That works with `scheme=kwargs["scheme"],` and `, adaptive=kwargs["adaptive"]` removed from `sol, info = eq.solve(state, ....` in `Evolve_scenario.py`.

Needs a pretty new version of `py-pde` though.

**Comment by HannoSpreeuw** [comment]
The `Final_distributions.pdf` plot is empty, though, so I need to dig into that.

**Comment by EmiliaJarochowska** [comment]
Is there anything in the Results file?

**Comment by HannoSpreeuw** [comment]
Yes there is also a hdf5 file, I will look into it.

**Comment by HannoSpreeuw** [comment]
As a side note - I picked up the result from a parallel run - `solver: str   = "crank-nicolson"` yielded

```
raise ConvergenceError("Crank-Nicolson step did not converge.")
```
at 34% of the integration time (=30 times T*)

**Comment by HannoSpreeuw** [comment]
The `solver: str   = "adams–bashforth"` run showed an empty plot because all saved values - except at t=0 - are nans.
So it seems this integration method derails within 1% of T* - data at 3001 times, covering 30 times T* have been saved.

I guess we need an implicit scheme to solve for this code modification, this would require branching off `Use_solve_ivp_without_py-pde_wrapper`.
To be continued tomorrow.

**Comment by HannoSpreeuw** [comment]
Alternatively, we could settle for integrating over 10 times T*, with `"crank-nicolson"`, that should just about complete, since this is 33.33% of T*.
Running that now, to see if this yields anything sane.

**Comment by HannoSpreeuw** [comment]
Yields an interesting plot. After 10 times T* calcite starts to derail while the other four quantities are still physically possible.
![Final_distributions](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/assets/11661087/b0be2933-e574-478b-829f-bc4f2b01d62c)

**Comment by EmiliaJarochowska** [comment]
It seems you have reproduced the oscillations in #40 so I would like to suggest merging this branch [after applying the version of the bottom boundary condition that is in agreement with the rhytmite](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/issues/40#issuecomment-2244565907).

**Comment by HannoSpreeuw** [comment]
That should be okay after we have agreed on the best i.e. least worrying, ad-hoc bottom boundary condition for aragonite and calcite.
