### ISSUE TITLE
Investigate the differences between marlpde and rhytmite when the same solver and initial settings are used

### ISSUE THREAD

**Issue by EmiliaJarochowska** [astro-turing/Integrating-diagenetic-equations-using-Python#40]
We want to understand why marlpde and [rhytmite](https://github.com/cedrict/rhythmite) give different results for runs longer than 1 dt when the same solver settings are used.

This can be done by fixing the solver and the parameters and focusing on why the results still differ. I suggest focusing on Euler using a fixed time time step of 1e-6. But if needed, a comparison of RK23, RK45 or adaptive could also be done. Important is to do one comparison at a time.

This should be done with the corrected typo as in #39 so using the `Oscillations_like_Fortran` branch. Additional adjustment can be made, either to marlpde or to rhytmite, e.g. the clipping of values, to pinpoint the causes of differences.

Here is a comparison using the Euler solver after 100 dt, made by Charlotte (email from 13 June):

![image](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/assets/18270548/8e929e80-1284-45da-8ca2-61aa9f2e6a59)

**Comment by EmiliaJarochowska** [comment]
The differences are small but you can use the code for plotting residues in https://github.com/MindTheGap-ERC/Cross-comparison to investigate them

**Comment by HannoSpreeuw** [comment]
Okay, I guess this [committed comparison plot, from the day before, i.e. June 12](https://github.com/MindTheGap-ERC/Cross-comparison/blob/main/dt100/comp_t_100_py_pde.png) was also made using the main marlpde branch, i.e. with the correct formula for the porosity diffusion coefficient instead of the restored typo.

And I guess including the default solver settings from the main marlpde branch.

I will use new folders to upload comparisons coming from anything different from the main marlpde branch.

**Comment by HannoSpreeuw** [comment]
![res_t_1_py_pde](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/assets/11661087/2ad27173-0d6c-4d48-82d9-571e08b25827)

Better resemblance now near the surface and away from the ADZ.

See [these two commits](https://github.com/MindTheGap-ERC/Cross-comparison/compare/main...code_changes_emerging_from_rhythmite_marlpde_comparison) for some background.

**Comment by EmiliaJarochowska** [comment]
That is indeed very good, considering that we are interested in what is exported from the system, some discrepancy in the ADZ is probably acceptable, as long as the values converge in the lower part of the system. Any ideas what the causes of the remaining differences might be?

**Comment by HannoSpreeuw** [comment]
I guess the remaining differences can be explained by either:

- slightly different position of the rhythmite ADZ wrt marlpde, since the rhythmite grid is shifted wrt marlpde: marlpde effectuates boundary conditions at the beginning of the first cell and at the end of the last - e.g. index = -0.5 for the surface - while rhythmite does so at the centers of the first and last cells.
- different calculation of the CA and CC spatial derivatives

I can continue investigating this in a week from now.

**Comment by HannoSpreeuw** [comment]
In order to resolve the remaining differences the simplest approach would be to align the rhythmite and marlpde grids, since they are half a cell apart. 
Aligning the grids would likely result in a closer resemblance than the linear interpolation added to the comparison code through [this commit](https://github.com/MindTheGap-ERC/Cross-comparison/commit/597e0b0379abfa68946027a5a5f08d19dfaf544e).

Aligning the grids is impossible without changing the way rhythmite effectuates the boundary conditions, since these are imposed at cell centers, not at cell edges.

**Comment by HannoSpreeuw** [comment]
However, `nnx = 1000` will make rhythmite exit with `nan encountered, exiting`.

**Comment by HannoSpreeuw** [comment]
Tried a different approach. No ADZ ---> No clamping is needed in rhythmite. This makes an integration over T* possible. These are the differences between rhythmite and marlpde.

![res_t_1_py_pde](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/assets/11661087/20970f99-886f-4cf6-adf2-18256f0a419c)

See [this commit](https://github.com/MindTheGap-ERC/Cross-comparison/commit/60d7f4cf97bf498be877af73159840dfada31f76) for the code.

**Comment by EmiliaJarochowska** [comment]
Here's what I received from Charlotte:

> Rhythmite can be run at higher resolutions as it is, but the timestep needs to be decreased to keep it stable, I found that with dt=10-7, it can do at least 800 nnx without issue.

**Comment by HannoSpreeuw** [comment]
Okay, thanks, I hadn't changed the time step.

For such a large depth grid one will probably need to run this on a powerful cluster node, if one wants to integrate over an interval appreciably longer than 1e-4 times T*.

**Comment by EmiliaJarochowska** [comment]
Turns out Charlotte has ran the comparison for the steady-state solution (Fig. 3) with different grid sizes (200 to 1000 by 100) and the agreement between rhytmite and marlpde is excellent. There are only very tiny differences at the surface of the system, which is not a problem.

**Comment by EmiliaJarochowska** [comment]
@HannoSpreeuw observed that if clamping of non-physical values is removed from rhytmite, then integration over longer times (as in T*) is not possible, unless one also switches off ADZ. So clamping of unphysical values seems crucial, but is it possible to obtain solutions without it? According to Cedric, if intermittent values are unphysical but the final result is, then they are acceptable as an approximation of the solver.
I added @csummers25 here btw :-)

**Comment by HannoSpreeuw** [comment]
Here is yet another way of assessing differences between marlpde and rhythmite.
This time a 250 ka run, with initial and surface porosities of 0.8.
In marlpde/parameters.py
`    
solver: str   = "explicit"
scheme: str   = "rk"
`

After some 133978 years one runs into

`
RuntimeError: Time step below 1e-10
54%|███████████████████████████████████████████▍                                     | 10.15751/18.953752843062926
`

Now this time of 133978 years may coincide with the calcite bump prior to oscillations from the slides from @csummers25 

What does this mean? 
marlpde tries to enforce a `tolerance=0.0001` but that would yield a time step  < 1e-10 when the calcite composition becomes almost 1?

But there is a need to verify that also marlpde's calcite composition at the time of bombing out (~133978 years) is almost 1, i.e. in agreement with rhythmite's value at that same time.

I will try an Eulerian scheme as well.

**Comment by HannoSpreeuw** [comment]
Same result for
 `scheme: str   = "euler"`, 
slighty earlier, i.e.
 
```
54% --> 53%

10.15751 --> 10.12714
```

**Comment by HannoSpreeuw** [comment]
With `solver: str   = "scipy"` in `marlpde/parameters.py` and `method="LSODA", first_step=1e-6, atol=1e-3`:

> RuntimeError: Encountered Not-A-Number (NaN) in evolution
 53%|███████████████████████████████████████████▍                                      | 10.04276/18.953752843062926
 
 So a similar result.

**Comment by HannoSpreeuw** [comment]
A possible way out would be to add clamping to physically feasible values to marlpde and see if it can integrate beyond this point.

**Comment by HannoSpreeuw** [comment]
Clamping does not seem to be needed to integrate over 250,000 years if implicit solvers -with numerically approximated instead of functional Jacobians - in marlpde's updated [Use_solve_ivp_without_py-pde_wrapper](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/tree/Use_solve_ivp_without_py-pde_wrapper) branch is used.

I find these solutions at 50 cm depth over that time interval - i.e. no oscillations:

![At_50_cm_depth_over_250_000_years](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/assets/11661087/0aaa2a87-74c8-41e5-a5f0-9207f609c9be)

**Comment by HannoSpreeuw** [comment]
With a constant porosity diffusion coefficient and the implicit "BDF" solver, those profiles at 50 cm depth are even flatter.

![At_50_cm_depth_over_250_000_years_BDF_no_py-pde_wrapper](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/assets/11661087/4d288509-8512-4dda-9915-f12f812859ef)

**Comment by HannoSpreeuw** [comment]
Does rhythmite have a [varying porosity diffusion coefficient](https://github.com/MindTheGap-ERC/rhythmite/blob/1701970bd4a5203454c18aab9d4bb24c49ed3a92/DiagenesisModel.py#L142)?

**Comment by EmiliaJarochowska** [comment]
Yes, please see https://github.com/cedrict/rhythmite/blob/257136bec97acc283dbc9e682c7fcf6b8669b387/DiagenesisModel.py#L142-L144

**Comment by HannoSpreeuw** [comment]
Almost the same link.

**Comment by csummers25** [comment]
It doesn't vary during the simulation, the value is just calculated from the other parameters initially

**Comment by HannoSpreeuw** [comment]
Ah, now I see, sorry for the oversight.

**Comment by HannoSpreeuw** [comment]
In an effort to mimick the bottom boundary condition for aragonite and calcite used by rhyhtmite, I added [commit 73b91b4](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/commit/73b91b499baf91005d051f564622f5f41e398367). 

See the log message of that commit to understand why it may be closer to the rhythmite solution for the missing bottom boundary conditions for aragonite and calcite than the dummy `curvature=0` bottom boundary condition from [commit c1d98ae](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/commit/c1d98ae8b6550b50083677af8e3d5939a439bf0d).

The result is similar, though.

![Oscillations_from_marlpde_using_Oscillations_like_Fortran_branch_commit_73b91b4](https://github.com/user-attachments/assets/64a190c9-9915-45fb-8e38-3b1706b963ef)

**Comment by HannoSpreeuw** [comment]
Plotting script.
```
import numpy as np
import h5py
import pylab as pyl

pyl.clf()
hf = h5py.File('LMAHeureuxPorosityDiff.hdf5', 'r')
data = np.array(hf["data"])
times = np.array(hf["times"])
times.shape
data = np.moveaxis(data, 0, -1)
data.shape
ms = 3
pyl.title("Compositions, concentrations and porosity over 250 ka at 50 cm depth, commit hash", fontsize=9)
pyl.plot(np.linspace(0,1,data.shape[2])*2.5e5, data[0, 20, :], "v", ms = ms, label = "CA")
pyl.plot(np.linspace(0,1,data.shape[2])*2.5e5, data[1, 20, :], "^", ms = ms, label = "CC")
pyl.plot(np.linspace(0,1,data.shape[2])*2.5e5, data[2, 20, :],  ">", ms = ms, label = "cCa")
pyl.plot(np.linspace(0,1,data.shape[2])*2.5e5, data[3, 20, :], "<", ms = ms, label = "cCO3" )
pyl.plot(np.linspace(0,1,data.shape[2])*2.5e5, data[4, 20, :], "o", ms = ms, label = "Phi")
pyl.legend(loc='lower left')
pyl.savefig("Oscillations_from_marlpde_using_Oscillations_like_Fortran_branch_commit_hash.png", bbox_inches="tight")
```

**Comment by HannoSpreeuw** [comment]
[Commit 24cd1b5](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/commit/24cd1b5f3016196df40a3b8fc0f852a7f4fd30f7) has a slope=0 imposed on the aragonite and calcite profiles at the bottom, instead of a second order derivative=0 or instead of slope=adjacent_value, which should mimick rhythmite.

The oscillations are again similar.

![Oscillations_from_marlpde_using_Oscillations_like_Fortran_branch_commit_24cd1b5](https://github.com/user-attachments/assets/90bf726c-cd16-4a11-b615-e3a1d0b0a8f9)

**Comment by HannoSpreeuw** [comment]
[Doubling the grid dimension, from 5m to 10m, while retaining the depth resolution](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/commit/7e73aa748903ec49140dbdf04d8606f342eaea78) makes the oscillations vanish.

![Oscillations_from_marlpde_using_Oscillations_like_Fortran_branch_commit_7e73aa7](https://github.com/user-attachments/assets/88c0a1aa-c88d-486b-8508-8ee7f12721d2)

**Comment by HannoSpreeuw** [comment]
And a similar result with a [curvature=0 ad-hoc bottom boundary condition for aragonite and calcite](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/commit/05ae9803366cb6671cdbc4f9425b8837d5486ee5):

![Oscillations_from_marlpde_using_Oscillations_like_Fortran_branch_commit_05ae980](https://github.com/user-attachments/assets/7d26a87f-7abd-4b91-9e33-066c73ae64a8)

**Comment by EmiliaJarochowska** [comment]
Thank you for this thorough investigation. 
How to apply the conclusions? I would like to suggest reverting the typo into the code of marlpde to the correct form (**3) and adjusting `b` accordingly, as it has been done in rhytmite, for consistency.
As the purpose of marlpde was to reproduce the oscillations, I would like to merge a version of the boundary conditions that allow that. @HannoSpreeuw  you have found several, in the pursuit of mimicking rhytmite. Would [this commit](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/commit/24cd1b5f3016196df40a3b8fc0f852a7f4fd30f7) be the right version of the code to merge?

**Comment by HannoSpreeuw** [comment]
Seems good to merge with main after reverting the typo etc.

The most suitable commit to merge with main depends on the result of [this discussion](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/issues/39#issuecomment-2245451211), I guess.

**Comment by HannoSpreeuw** [comment]
I am currently running marlpde with a debugger - and breakpoints in `pde/grids/boundaries/local.py` -  to figure out how 

```
        self.bc_CA = [{"value": CA0}, 
                      {"derivative_expression" : \
                       lambda adjacent_value, dx, x, t: adjacent_value}]
        self.bc_CC = [{"value": CC0}, 
                      {"derivative_expression" : \
                       lambda adjacent_value, dx, x, t: adjacent_value}]   
```

propagates, i.e. how marlpde computes spatial derivatives at the bottom for aragonite and calcite.

The debugger says `adjacent_value=0`.

Also `value_func(adjacent_value, dx, *args)` from [` return dx * value_func(adjacent_value, dx, *args) + adjacent_value`](https://github.com/zwicker-group/py-pde/blob/8630bc58e0f140983266a99bc184baddc86b57e5/pde/grids/boundaries/local.py#L1315) is 0.

**Comment by HannoSpreeuw** [comment]
Similar results from

```
        self.bc_CA = [{"value": CA0}, 
                      {"value_expression" : \
                       lambda adjacent_value, dx, x, t: adjacent_value}]
        self.bc_CC = [{"value": CC0}, 
                      {"value_expression" : \
                       lambda adjacent_value, dx, x, t: adjacent_value}] 
```

i.e. `adjacent_value=array(0.)` and `value_func(adjacent_value, *args)=array(0.)`.
(`value_func(adjacent_value, *args)` from [this line](https://github.com/zwicker-group/py-pde/blob/8630bc58e0f140983266a99bc184baddc86b57e5/pde/grids/boundaries/local.py#L1315).)

With "derivative_expression", I could understand why the spatial derivatives at the bottom should be zero, since we started off with flat initial distribiutions for calcite and aragonite, but for "value_expression" I don't understand the zeros, e.g. why `adjacent_value`  should be zero.

**Comment by HannoSpreeuw** [comment]
Anyway, I just realised that if we are to mimic rhythmite, [which has the spatial derivatives at the deepest node equal to spatial derivatives at the second deepest node](https://github.com/cedrict/rhythmite/discussions/4#discussioncomment-10031967), this is effectively a second spatial derivative=0, i.e. we are back at the `curvature=0` bottom boundary condition for aragonite and calcite. This is [commit c1d98ae](https://github.com/astro-turing/Integrating-diagenetic-equations-using-Python/commit/c1d98ae8b6550b50083677af8e3d5939a439bf0d).

So I am going for that commit - with some updates - to be merged with main.

**Comment by EmiliaJarochowska** [comment]
Thanks for checking this. So we can go back to that commit, but please use the correct (as per the article) version of the porosity diffusion coefficient (`**3`) and adjust `b` instead

**Comment by HannoSpreeuw** [comment]
But set a default value of `b=5e-4` when merging with `main`, I reckon?

**Comment by EmiliaJarochowska** [comment]
As mentioned in the PR, it has no meaning if you don't use the typo, so hardly a "default" but yes. My concern was that if a user wants to reproduce the oscillations, they will need to change it. So perhaps there is some value in helping the users through the maze of the parameters by setting the defaults as used in our runs for oscillations. But I won't die on this hill.

**Comment by HannoSpreeuw** [comment]
@EmiliaJarochowska I guess this investigation is completed and we can close this issue.
